## General Config
appiumServerURL=http://127.0.0.1:4723
retryFailureCount=1
swipeRate=300

## Platform Capabilities
platformType= Android

android_platformVersion=16.0
ios_platformVersion=26.4

android_automationDriver=UiAutomator2
ios_automationDriver=XCUITEST

## Devices Capabilities
android_deviceName=emulator-5554
android_deviceID=emulator-5554

ios_deviceName=iPhone Air
ios_deviceID=C50D93BD-C6C2-4F1A-B00B-2454DEC70C00

## Application Capabilities
android_appPackage=com.swaglabsmobileapp
android_appActivity=com.swaglabsmobileapp.SplashActivity
android_appInstaller=Android.SauceLabs.apk

ios_bundleId=com.saucelabs.SwagLabsMobileApp
ios_appInstaller=iOS.Simulator.SauceLabs.zip

## General Capabilities
autoGrantPermission=true
noReset=false
fullReset=false